{% set name = "asv" %}
{% set version = "0.4.2a20210604" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/airspeed-velocity/asv/archive/ef016e233cb9a0b19d517135104f49e0a3c380e9.tar.gz
  sha256: 9200aeaa1e7e37b2e85f8c50449aec7ece1796bb477a4b5236b1f3d8a4d1d2b0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - sphinx
    - sphinx_bootstrap_theme
    - six
  run:
    - python
    - setuptools
    - six

test:
  imports:
    - asv
#  requires:
#    - pytest
#  files:
#    - {{ SRC_DIR }}/test/
#  commands:
#    - cd {{ SRC_DIR }}/test/
#    - py.test

about:
  home: https://github.com/spacetelescope/asv
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: A simple Python benchmarking tool with web-based reporting

  description: |
    It is primarily designed to benchmark a single project over its lifetime
    using a given suite of benchmarks. The results are displayed in an
    interactive web frontend that requires only a basic static webserver to
    host.
  doc_url: http://asv.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/spacetelescope/asv

extra:
  recipe-maintainers:
    - CJ-Wright
    - saraedum
